name: Build and upload artifact
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package application.zip
        run: |
          ls application
          cd application
          zip -r application.zip ./*
          mv application.zip ../application.zip
          cd ..
          zip -r openkaios-store-nightly.zip application.zip metadata.json
          mkdir workdir
          mv application.zip workdir/application.zip
          mv metadata.json workdir/metadata.json

      - name: Build artifact
        uses: actions/upload-artifact@v2
        with:
          name: bilibili_kaios-omnisd-nightly
          path: ./workdir/*
