name: Build and upload artifact
on: push

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: npm install

      - name: build
        run: npm run package

      - uses: actions/upload-artifact@v2
        with:
          name: App
          path: build/bhacker-store.zip
