name: Build and upload artifact
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Package application.zip (openGiraffes Database)
        run: |
          ls application
          cd application
          zip -r application.zip ./*
          mv application.zip ../application.zip
          cd ..
          mkdir workdir
          mv application.zip workdir/application.zip
          cp metadata.json workdir/metadata.json

      - name: Build artifact (openGiraffes Database)
        uses: actions/upload-artifact@v2
        with:
          name: openGiraffes-store-openGiraffes-nightly
          path: ./workdir/*
          
      - name: Package application.zip (bHackers Database)
        run: |
          cp databases/manifest-bhackers.webapp application/manifest.webapp
          cp databases/server-info-bhackers.js application/js/server-info.js
          ls application
          cd application
          zip -r application.zip ./*
          mv application.zip ../application.zip
          cd ..
          mkdir workdir2
          mv application.zip workdir2/application.zip
          cp metadata.json workdir2/metadata.json

      - name: Build artifact (bHackers Database)
        uses: actions/upload-artifact@v2
        with:
          name: openGiraffes-store-bHackers-nightly
          path: ./workdir2/*

