name: Prettier - Check Code Formatting
on: push

jobs:
  check-formatting:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: npm install

      - name: check formatting
        run: npm run formatting:test
